<a href="https://colab.research.google.com/github/sajjaporn-sr/My-coursework/blob/main/SS_Iris_Dataset_Analysis_KNN_vs_K_Means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Description**: A comparative study between K-Nearest Neighbors (KNN) and K-Means Clustering using the classic Iris dataset.

**Tools Used**: Python, Scikit-learn, Pandas.

**Key Learning**: Implementing Supervised (KNN) vs. Unsupervised (K-Means) learning workflows.

# **Part 1: K-Nearest Neighbors (KNN) Classification**

## **import dataset from kaggle**

In [ ]:
!mkdir ~/.kaggle
!cp kaggle (1).json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle (1).json
!kaggle datasets download uciml/iris

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `cp kaggle (1).json ~/.kaggle/'
/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `chmod 600 ~/.kaggle/kaggle (1).json'
Dataset URL: https://www.kaggle.com/datasets/uciml/iris
License(s): CC0-1.0
Downloading iris.zip to /content
  0% 0.00/3.60k [00:00<?, ?B/s]
100% 3.60k/3.60k [00:00<00:00, 5.28MB/s]

In [ ]:
!unzip iris.zip

Archive:  iris.zip
  inflating: Iris.csv
  inflating: database.sqlite

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
iris = pd.read_csv('Iris.csv')

In [ ]:
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

## **Preprocessing**

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

X = iris.drop('Species', axis=1)
X = X.drop('Id', axis=1)
y = iris['Species']

le = LabelEncoder()
y = le.fit_transform(iris['Species'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## **Train and test model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#Euclidean Distance  euclidean
#Manhattan Distance  cityblock
#Minkowski Distance (with p=3)  minkowski
#Cosine Similarity  cosine
#Chebyshev Distance  chebyshev

A = ['euclidean','cityblock','minkowski','cosine','chebyshev']
Y = []
for i in A:
  knnClassifier = KNeighborsClassifier(n_neighbors = 3, metric = i)
  knnClassifier.fit(X_train, y_train)
  Y.append(knnClassifier.predict(X_test))

Y = np.array(Y).T
y_pred_euclidean , y_pred_manhattan , y_pred_minkowski , y_pred_cosine , y_pred_chebyshev = Y[:,0] , Y[:,1] , Y[:,2] , Y[:,3] , Y[:,4]

df = pd.DataFrame(
    {
        "Distance Metric":['euclidean','manhattan','minkowski','cosine','chebyshev'],
        "Accuracy":[accuracy_score(y_pred_euclidean,y_test),accuracy_score(y_pred_manhattan,y_test),accuracy_score(y_pred_minkowski,y_test),accuracy_score(y_pred_cosine,y_test),accuracy_score(y_pred_chebyshev,y_test)]
    })
df

  Distance Metric  Accuracy
0       euclidean  0.966667
1       manhattan  1.000000
2       minkowski  0.966667
3          cosine  0.966667
4       chebyshev  1.000000

# **Part 2: K-means Clustering**

In [ ]:
X = iris
X = X.drop('Id', axis=1)
X_0 = (X[X['Species']=='Iris-setosa'].drop('Species', axis=1))
X_1 = (X[X['Species']=='Iris-versicolor'].drop('Species', axis=1))
X_2 = (X[X['Species']=='Iris-virginica'].drop('Species', axis=1))

centroid0 = np.array(np.sum(X_0,axis=0)/len(X_0))
centroid1 = np.array(np.sum(X_1,axis=0)/len(X_1))
centroid2 = np.array(np.sum(X_2,axis=0)/len(X_2))

X_0 = X_0.to_numpy()
X_1 = X_1.to_numpy()
X_2 = X_2.to_numpy()


def euclidean_distance(u,v):
  return (np.sum((u-v)**2))**0.5

distortion_euclidean = 0
for x in X_0:
  distortion_euclidean += euclidean_distance(x,centroid0)
for x in X_1:
  distortion_euclidean += euclidean_distance(x,centroid1)
for x in X_2:
  distortion_euclidean += euclidean_distance(x,centroid2)

def manhattan_distance(u,v):
  return np.sum(np.abs(u-v))

distortion_manhattan = 0
for x in X_0:
  distortion_manhattan += manhattan_distance(x,centroid0)
for x in X_1:
  distortion_manhattan += manhattan_distance(x,centroid1)
for x in X_2:
  distortion_manhattan += manhattan_distance(x,centroid2)

def minkowski_distance(u,v):
  return np.sum(np.abs(u-v)**3)**(1/3)

distortion_minkowski = 0
for x in X_0:
  distortion_minkowski += minkowski_distance(x,centroid0)
for x in X_1:
  distortion_minkowski += minkowski_distance(x,centroid1)
for x in X_2:
  distortion_minkowski += minkowski_distance(x,centroid2)

def cosine_distance(u,v):
  return np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))

distortion_cosine = 0
for x in X_0:
  distortion_cosine += cosine_distance(x,centroid0)
for x in X_1:
  distortion_cosine += cosine_distance(x,centroid1)
for x in X_2:
  distortion_cosine += cosine_distance(x,centroid2)

def chebyshev_distance(u,v):
  return np.max(np.abs(u-v))

distortion_chebyshev = 0
for x in X_0:
  distortion_chebyshev += chebyshev_distance(x,centroid0)
for x in X_1:
  distortion_chebyshev += chebyshev_distance(x,centroid1)
for x in X_2:
  distortion_chebyshev += chebyshev_distance(x,centroid2)

df = pd.DataFrame(
    {
        "Distance Metric":['euclidean','manhattan','minkowski','cosine','chebyshev'],
        "Distortion":[distortion_euclidean,distortion_manhattan,distortion_minkowski,distortion_cosine,distortion_chebyshev]
    })
df

  Distance Metric  Distortion
0       euclidean  100.517093
1       manhattan  169.984000
2       minkowski   88.169132
3          cosine  149.831634
4       chebyshev   78.216000